FLOOR_STYLE = {
    "dark": "dark_floor_texture.png",
    "rustic": "rustic_floor.png",
    "light-gray": "light-gray-floor-tile.png",
    "white-marble": "white_marble_floor.png",
    "wood-plank": "seamless_wood_planks_floor.png",
    "brown-ceramic": "brown_ceramic_tile.png",
    "gray-ceramic": "gray_ceramic_tile.png",
    "tile_grigia_caldera": "tile_grigia_caldera_porcelain_floor.png",
    "table-light-wood": "table_light_wood.png",
    "stucco": "stucco_wall.png",
    "smooth-light-gray-plaster": "smooth_light_gray_plaster.png",
    "new-light-gray-plaster": "new_light_gray_plaster.png",
    "meeka-beige-plaster": "meeka-beige-plaster.png",
    "marble": "marble_floor.png",
    "martin-novak-wood-table": "martin_novak_wood_table.png",
    "light-grey-plaster": "light_grey_plaster.png",
    "light-gray-plaster-alt": "light_gray_plaster.png",
    "light": "light_floor.png",
    "kona-gotham": "kona_gotham.png",
    "grigia-caldera-porcelain": "grigia_caldera_porcelain_floor.png",
    "gray": "gray_wall.png",
    "gray-floor": "gray_floor.png",
    "dapper-gray": "dapper_gray_floor.png",
    "cream-plaster": "cream-plaster.png",
    "capriccio-sky": "capriccio_sky.png",
    "canvas-sky-blue": "canvas_sky_blue.png",
    "blue_cloth": "blue_cloth.png",
    "blue_gingham": "blue_gingham.png",
    "green_gingham": "green_gingham.png",
    "pink_gingham": "pink_gingham.png",
    "green_flower": "green_flower.png",
    "blue_flower": "blue_flower.png",
    "yellow_bee": "yellow_bee.png",
    "purple_cross": "purple_cross.png",
    "pink_flower": "pink_flower.png",
    "roses": "roses.png",
    "pink_white_flower": "pink_white_flower.png",
    "GraspVLA": "GraspVLA.png"
}

WALL_STYLE = {
    "light-blue": "light_blue_wall.png",
    "dark-blue": "dark_blue_wall.png",
    "dark-gray-plaster": "dark_gray_plaster.png",
    "gray-plaster": "gray_plaster.png",
    "dark-green": "dark_green_plaster_wall.png",
    "light-gray-plaster": "light-gray-plaster.png",
    "ceramic": "ceramic.png",
    "white": "white_wall.png",
    "yellow-linen": "yellow_linen_wall_texture.png",
    "table-light-wood": "table_light_wood.png",
    "stucco": "stucco_wall.png",
    "smooth-light-gray-plaster": "smooth_light_gray_plaster.png",
    "new-light-gray-plaster": "new_light_gray_plaster.png",
    "meeka-beige-plaster": "meeka-beige-plaster.png",
    "marble": "marble_floor.png",
    "martin-novak-wood-table": "martin_novak_wood_table.png",
    "light-grey-plaster": "light_grey_plaster.png",
    "light-gray-plaster-alt": "light_gray_plaster.png",
    "light": "light_floor.png",
    "kona-gotham": "kona_gotham.png",
    "grigia-caldera-porcelain": "grigia_caldera_porcelain_floor.png",
    "gray": "gray_wall.png",
    "gray-floor": "gray_floor.png",
    "dapper-gray": "dapper_gray_floor.png",
    "cream-plaster": "cream-plaster.png",
    "capriccio-sky": "capriccio_sky.png",
    "canvas-sky-blue": "canvas_sky_blue.png",
    "dark": "dark_floor_texture.png",
    "rustic": "rustic_floor.png",
    "light-gray": "light-gray-floor-tile.png",
    "white-marble": "white_marble_floor.png",
    "wood-plank": "seamless_wood_planks_floor.png",
    "brown-ceramic": "brown_ceramic_tile.png",
    "gray-ceramic": "gray_ceramic_tile.png",
    "tile_grigia_caldera": "tile_grigia_caldera_porcelain_floor.png",
    "blue_cloth": "blue_cloth.png",
    "blue_gingham": "blue_gingham.png",
    "green_gingham": "green_gingham.png",
    "pink_gingham": "pink_gingham.png",
    "green_flower": "green_flower.png",
    "blue_flower": "blue_flower.png",
    "yellow_bee": "yellow_bee.png",
    "purple_cross": "purple_cross.png",
    "pink_flower": "pink_flower.png",
    "roses": "roses.png",
    "pink_white_flower": "pink_white_flower.png",
    "GraspVLA": "GraspVLA.png"
}


STYLE_MAPPING = {"floor": FLOOR_STYLE, "wall": WALL_STYLE}


def get_texture_filename(type, style):
    assert type in STYLE_MAPPING.keys()
    assert style in STYLE_MAPPING[type].keys()
    return STYLE_MAPPING[type][style]
